import fs from 'node:fs/promises';
import fsSync from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import sharp from 'sharp';
import opentype from 'opentype.js';

const WIDTH = 1055;
const HEIGHT = 1491;
const TEMPLATE = path.resolve('public/master-template.png');
const GENERATED_DIR = process.env.VERCEL ? path.resolve('/tmp/generated') : path.resolve('storage/generated');

const COLORS = {
  green: '#0b4939'
};

function toArrayBuffer(buf) {
  const ab = new ArrayBuffer(buf.length);
  const view = new Uint8Array(ab);
  for (let i = 0; i < buf.length; ++i) {
    view[i] = buf[i];
  }
  return ab;
}

// Load fonts synchronously at module init so vector paths are generated without Vercel fontconfig dependencies
const serifBuffer = fsSync.readFileSync(path.resolve('src/fonts/Serif-Bold.ttf'));
const monoBuffer = fsSync.readFileSync(path.resolve('src/fonts/Mono-Bold.ttf'));

const serifFont = opentype.parse(toArrayBuffer(serifBuffer));
const monoFont = opentype.parse(toArrayBuffer(monoBuffer));

function fitTextPath(font, text, x, y, startSize, minSize, maxWidth) {
  const str = String(text || '').trim();
  if (!str) return '';

  for (let size = startSize; size >= minSize; size -= 1) {
    const p = font.getPath(str, x, y, size);
    const box = p.getBoundingBox();
    if (box.x2 - box.x1 <= maxWidth) {
      p.fill = COLORS.green;
      return p.toSVG(4);
    }
  }
  let trunc = str;
  while (trunc.length > 3) {
    trunc = trunc.slice(0, -1);
    const p = font.getPath(trunc + '…', x, y, minSize);
    const box = p.getBoundingBox();
    if (box.x2 - box.x1 <= maxWidth) {
      p.fill = COLORS.green;
      return p.toSVG(4);
    }
  }
  const p = font.getPath(str, x, y, minSize);
  p.fill = COLORS.green;
  return p.toSVG(4);
}

async function photoLayer(photoInput) {
  const diameter = 430;
  const left = 303;
  const top = 255;
  const input = await sharp(photoInput)
    .rotate()
    .resize(diameter, diameter, { fit: 'cover', position: 'attention' })
    .png()
    .toBuffer();

  const mask = Buffer.from(
    `<svg width="${diameter}" height="${diameter}" xmlns="http://www.w3.org/2000/svg"><circle cx="${diameter / 2}" cy="${diameter / 2}" r="${diameter / 2 - 2}" fill="white"/></svg>`
  );

  const circle = await sharp(input)
    .composite([{ input: mask, blend: 'dest-in' }])
    .png()
    .toBuffer();

  return { input: circle, left, top };
}

export async function renderBuilderCard({ photoPath, photoBuffer, name, builderId, teamName }) {
  await fs.mkdir(GENERATED_DIR, { recursive: true });

  const displayName = String(name || '').trim().toUpperCase();
  const displayTeam = String(teamName || '').trim().toUpperCase();
  const displayId = String(builderId || '').trim().toUpperCase();

  console.log('[CARD RENDERER] Input Data:', {
    name: displayName,
    builderId: displayId,
    teamName: displayTeam,
    hasPhoto: Boolean(photoPath || photoBuffer)
  });

  const nameSvgPath = fitTextPath(serifFont, displayName, 360, 1222, 38, 18, 500);
  const idSvgPath = fitTextPath(monoFont, displayId, 425, 1283, 32, 16, 440);
  const teamSvgPath = fitTextPath(serifFont, displayTeam, 445, 1344, 36, 18, 420);

  const overlays = [];

  const photoInput = photoBuffer || photoPath;
  if (photoInput) {
    overlays.push(await photoLayer(photoInput));
  }

  // Pure SVG vector paths generated by opentype.js - 100% independent of Vercel fontconfig / system fonts
  const textSvg = `
    <svg width="${WIDTH}" height="${HEIGHT}" viewBox="0 0 ${WIDTH} ${HEIGHT}" xmlns="http://www.w3.org/2000/svg">
      ${nameSvgPath}
      ${idSvgPath}
      ${teamSvgPath}
    </svg>
  `;
  overlays.push({ input: Buffer.from(textSvg), left: 0, top: 0 });

  const safeId = displayId.replace(/[^A-Z0-9-]/g, '_');
  const outputPath = path.join(GENERATED_DIR, `${safeId}.png`);

  const buffer = await sharp(TEMPLATE)
    .resize(WIDTH, HEIGHT, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } })
    .composite(overlays)
    .png({ compressionLevel: 9, adaptiveFiltering: true })
    .toBuffer();

  const tempPath = `${outputPath}.${crypto.randomUUID()}.tmp`;
  try {
    await fs.writeFile(tempPath, buffer);
    await fs.rename(tempPath, outputPath);
  } catch {
    await fs.writeFile(outputPath, buffer).catch(() => {});
  } finally {
    await fs.unlink(tempPath).catch(() => {});
  }

  return outputPath;
}

export const CARD_SIZE = { width: WIDTH, height: HEIGHT };
